/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package vitor_test.Acme_Go.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Filter - Filters are used to query requests.
 */

public class Filter {
    @JsonProperty("field")
    public String field;

    public Filter withField(String field) {
        this.field = field;
        return this;
    }
    
    @JsonProperty("matchtype")
    public String matchtype;

    public Filter withMatchtype(String matchtype) {
        this.matchtype = matchtype;
        return this;
    }
    
    @JsonProperty("value")
    public String value;

    public Filter withValue(String value) {
        this.value = value;
        return this;
    }
    
    public Filter(@JsonProperty("field") String field, @JsonProperty("matchtype") String matchtype, @JsonProperty("value") String value) {
        this.field = field;
        this.matchtype = matchtype;
        this.value = value;
  }
}
