/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package vitor_test.Acme_Go.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Success - The `Status` type defines a successful response.
 */

public class Success {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("success")
    public Boolean success;

    public Success withSuccess(Boolean success) {
        this.success = success;
        return this;
    }
    
    public Success(){}
}
