/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package vitor_test.Acme_Go.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UserInput - The details of a typical user account
 */

public class UserInput {
    @JsonProperty("country")
    public String country;

    public UserInput withCountry(String country) {
        this.country = country;
        return this;
    }
    
    @JsonProperty("email")
    public String email;

    public UserInput withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("firstname")
    public String firstname;

    public UserInput withFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }
    
    @JsonProperty("lastname")
    public String lastname;

    public UserInput withLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }
    
    @JsonProperty("nickname")
    public String nickname;

    public UserInput withNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }
    
    @JsonProperty("password")
    public String password;

    public UserInput withPassword(String password) {
        this.password = password;
        return this;
    }
    
    public UserInput(@JsonProperty("country") String country, @JsonProperty("email") String email, @JsonProperty("firstname") String firstname, @JsonProperty("lastname") String lastname, @JsonProperty("nickname") String nickname, @JsonProperty("password") String password) {
        this.country = country;
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.nickname = nickname;
        this.password = password;
  }
}
