/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package vitor_test.Acme_Go.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;
import vitor_test.Acme_Go.utils.DateTimeDeserializer;
import vitor_test.Acme_Go.utils.DateTimeSerializer;

/**
 * User - The details of a typical user account
 */

public class User {
    @JsonProperty("country")
    public String country;

    public User withCountry(String country) {
        this.country = country;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("createdate")
    public OffsetDateTime createdate;

    public User withCreatedate(OffsetDateTime createdate) {
        this.createdate = createdate;
        return this;
    }
    
    @JsonProperty("email")
    public String email;

    public User withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("firstname")
    public String firstname;

    public User withFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public User withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("lastname")
    public String lastname;

    public User withLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }
    
    @JsonProperty("nickname")
    public String nickname;

    public User withNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }
    
    @JsonProperty("password")
    public String password;

    public User withPassword(String password) {
        this.password = password;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updatedate")
    public OffsetDateTime updatedate;

    public User withUpdatedate(OffsetDateTime updatedate) {
        this.updatedate = updatedate;
        return this;
    }
    
    public User(@JsonProperty("country") String country, @JsonProperty("email") String email, @JsonProperty("firstname") String firstname, @JsonProperty("lastname") String lastname, @JsonProperty("nickname") String nickname, @JsonProperty("password") String password) {
        this.country = country;
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.nickname = nickname;
        this.password = password;
  }
}
