/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package vitor_test.Acme_Go.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Users - An array of users.
 */

public class Users {
    /**
     * A list of users to return.
     */
    @JsonProperty("users")
    public User[] users;

    public Users withUsers(User[] users) {
        this.users = users;
        return this;
    }
    
    public Users(@JsonProperty("users") User[] users) {
        this.users = users;
  }
}
