/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package vitor_test.Acme_Go;

import vitor_test.Acme_Go.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "0.1.0";
	public String sdkVersion = "1.1.0";
	public String genVersion = "2.82.0";
	
}