/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package vitor_test.Acme_Go.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import vitor_test.Acme_Go.utils.SpeakeasyMetadata;


public class UpdateUserv1Request {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public vitor_test.Acme_Go.models.shared.UserInput userInput;

    public UpdateUserv1Request withUserInput(vitor_test.Acme_Go.models.shared.UserInput userInput) {
        this.userInput = userInput;
        return this;
    }
    
    /**
     * UserID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public UpdateUserv1Request withId(String id) {
        this.id = id;
        return this;
    }
    
    public UpdateUserv1Request(@JsonProperty("UserInput") vitor_test.Acme_Go.models.shared.UserInput userInput, @JsonProperty("id") String id) {
        this.userInput = userInput;
        this.id = id;
  }
}
